#@TYPE: Machine
#@NAME: Nvidia Jetson Orin Nano 8GB SOM
#@DESCRIPTION: Nvidia Jetson Orin Nano 8GB module in P3768 carrier

MACHINEOVERRIDES =. "orin-nano-som:jetson-orin-nano-8gb:"

require conf/machine/p3768-0000-p3767-0003.conf
